channel_colors:
  sdcCy5: magenta
  sdcDAPIxmRFPm: blue
  sdcGFP: green
  sdcRFP590: red
  sdcYFP: yellow
file_extension: tif
magnification: 60
objects:
  cells:
    assigned_objects:
    - nuclei
    - cytoplasm
    measure_blobs: false
    measure_intensity:
    - sdcGFP
    - sdcDAPIxmRFPm
    measure_morphology: true
    measure_tracks: true
    segmentation_channel: sdcCy5
  cytoplasm:
    assigned_objects: []
    measure_blobs:
      channels:
      - sdcGFP
      settings:
        exclude_border: true
        max_sigma: 10
        min_sigma: 1
        num_sigma: 10
        overlap: 0.5
        threshold: 0.0003
    measure_intensity:
    - sdcGFP
    measure_morphology: true
    measure_tracks: false
  nuclei:
    assigned_objects: []
    measure_blobs: false
    measure_intensity:
    - sdcGFP
    - sdcDAPIxmRFPm
    measure_morphology: true
    measure_tracks: false
    segmentation_channel: sdcDAPIxmRFPm
paths:
  feature_path: /data/active/atschan/20211014_bio325_test/features
  hdf5_path: /data/active/atschan/20211014_bio325_test/hdf5
  illcorr_path: /data/active/atschan/illumination_correction/20211014_60x_oil
  img_path: /data/active/atschan/20211014_bio325_test/MIP
  temp_seg_path: /data/active/atschan/20211014_bio325_test/temp_segmentation

