channel_colors:
  sdcCy5: red
  sdcDAPIxmRFPm: blue
  sdcGFP: green
  sdcRFP590-JF549: red
  sdcYFP: yellow
file_extension: stk
magnification: 100
scaling: 6.15
illumination_correction: false
cellpose:
  nuclei:
    model: nuclei
    diameter: 150
    resample: true
    cellprob_threshold: -2.86
    flow_threshold: 7.5
    do_3D: true
    gpu: true
    min_size: 2500
    channel: sdcRFP590-JF549
    nuclei_channel: false
    apply_filter: true
  cytoplasm: false
objects:
  nuclei:
    assigned_objects: []
    measure_blobs:
      channels:
      - sdcRFP590-JF549
      settings:
        exclude_border: true
        max_sigma: 1.5
        min_sigma: 1.5
        num_sigma: 1
        overlap: 0.5
        threshold: 0.0016
    measure_intensity:
    - sdcGFP
    - sdcRFP590-JF549
    measure_morphology: true
    measure_tracks:
      max_distance: 125
      time_window: 3
      max_split_distance: 125
      max_gap_closing_distance: 125
      allow_splitting: false
      allow_merging: false
paths:
  feature_path: /home/adrian/mnt/active/20211109_clone_9/features
  hdf5_path: /home/adrian/mnt/active/20211109_clone_9/hdf5
  illcorr_path: /home/adrian/mnt/active/illumination_correction/20211014_60x_oil
  img_path: /home/adrian/mnt/active/20211109_clone_9/MIP
  temp_seg_path: /home/adrian/mnt/active/20211014_bio325_test/temp_segmentation

