channel_colors:
  sdcCy5: red
  sdcDAPIxmRFPm: blue
  sdc-GFP: green
  sdcRFP590-JF549: red
  sdcYFP: yellow
file_extension: stk
magnification: 60
microscope: visiscope
spacing:
- 1
- 1
- 15.38
scaling: 15.38
illumination_correction: false
cellpose:
  nuclei:
    model: nuclei
    diameter: 120
    resample: false
    cellprob_threshold: -2.86
    flow_threshold: 7.5
    do_3D: true
    gpu: true
    min_size: 2500
    channel: sdcRFP590-JF549
    nuclei_channel: false
    apply_filter: true
  cytoplasm: false
objects:
  nuclei:
    assigned_objects: []
    measure_blobs:
      channels:
        - sdcRFP590-JF549
      settings:
        exclude_border: true
        max_sigma: 2
        min_sigma: 2
        num_sigma: 1
        overlap: 0.5
        threshold: 0.0005
    measure_intensity:
    - sdcGFP
    - sdcRFP590-JF549
    measure_morphology: true
    measure_tracks:
      max_distance: 125
      time_window: 3
      max_split_distance: 125
      max_gap_closing_distance: 125
      allow_splitting: false
      allow_merging: false
paths:
  feature_path: /data/active/atschan/20220217_hiPSC_MS2/features
  hdf5_path: /data/active/atschan/20220217_hiPSC_MS2/hdf5
  illcorr_path: /data/active/atschan/illumination_correction/20211014_60x_oil
  img_path: /data/active/atschan/20220217_hiPSC_MS2/
  temp_seg_path: /data/active/atschan/20220217_hiPSC_MS2/temp_segmentation


